name: Jekyll Start Bootstrap Github pages starter template
markdown: kramdown

permalink: /blog/:year/:month/:day/:title

title: mikkoo.me


url: "https://mikkoo.me" # "https://mmoi.github.io/mikkoo"
baseurl: "/" # "/"

exclude: [sass]


collections:
  - jobs
  - projects
  - feats
