name: Jekyll Bulma Github pages starter template
markdown: kramdown

permalink: /blog/:year/:month/:day/:title

title: mikkoo.io


url: "https://mmoi.github.io" # "https://mmoi.github.io/mikkoo"
baseurl: "/mikkoo/" # "/"

exclude: [sass]


collections:
  - jobs
  - projects
  