name: Jekyll Bulma Github pages starter template
markdown: kramdown

permalink: /blog/:year/:month/:day/:title

title: mikkoo.io


url: "localhost:4000" # "https://mmoi.github.io/mikkoo"
baseurl: "/" # "/"

exclude: [sass]


collections:
  - jobs
  - projects
  